### ISSUE TITLE
FAIL: end_to_end.py

### ISSUE THREAD

**Issue by rex4539** [tatsuhiro-t/spdylay#151]
Latest master.

```
=============================================
   spdylay 1.4.1-DEV: tests/test-suite.log
=============================================

# TOTAL: 3
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: end_to_end.py
===================

No supported SPDY version was negotiated.
Could not connect to the host: localhost:25
Could not connect to the host: localhost:79
FCould not connect to the host: localhost:2
.No supported SPDY version was negotiated.
No supported SPDY version was negotiated.
FNo supported SPDY version was negotiated.
FFatal: EOF
reqnum=1, completed=0
Some requests were not processed. total=1, processed=0
FNo supported SPDY version was negotiated.
F
======================================================================
FAIL: testFailedRequests (__main__.EndToEndSpdy2Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./end_to_end.py", line 82, in testFailedRequests
    2, self.call('/', ['https://localhost:25/', 'http://localhost:79']))
AssertionError: 2 != 3

======================================================================
FAIL: testOneTimedOutRequest (__main__.EndToEndSpdy2Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./end_to_end.py", line 90, in testOneTimedOutRequest
    self.assertEquals(0, self.call('/', ['--timeout=20']))
AssertionError: 0 != 1

======================================================================
FAIL: testSimpleRequest (__main__.EndToEndSpdy2Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./end_to_end.py", line 74, in testSimpleRequest
    self.assertEquals(0, self.call('/', []))
AssertionError: 0 != 1

======================================================================
FAIL: testSimpleRequestSpdy3 (__main__.EndToEndSpdy2Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./end_to_end.py", line 77, in testSimpleRequestSpdy3
    self.assertEquals(0, self.call('/', ['-v', '-3']))
AssertionError: 0 != 1

======================================================================
FAIL: testSimpleRequest (__main__.EndToEndSpdy3Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./end_to_end.py", line 99, in testSimpleRequest
    self.assertEquals(0, self.call('/', ['-v']))
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 6 tests in 4.357s

FAILED (failures=5)
FAIL end_to_end.py (exit status: 1)
```

**Comment by nieder** [comment]
Also seeing this on macOS. That test also requires python(2), which many distros no longer carry.
